<?php 

echo "mostrar salas que tiene pedidas un profesor en particular";
echo "mostrar cuadro con salas solicitadas";
echo "se debe mostrar por año y semestre";
echo "secretaria y mayordomo pueden ver info de cualquier profe";
echo "profesor puede ver solo su info";

 ?>


//TABLAS

 CREATE TABLE USUSARIO
 (
   RUT CHAR(8) NOT NULL,
   DV VARCHAR(1) NOT NULL,
   PASS VARCHAR (20) NOT NULL,
   TIPOUSUARIO VARCHAR (20) NOT NULL
 );

ALTER TABLE  USUARIO
ADD CONSTRAINT PK_USUARIO PRIMARY KEY (RUT);


 CREATE TABLE SECRETARIA
 (
   RUTSECRE CHAR(8) NOT NULL,
   DVSECRE VARCHAR(1) NOT NULL,
   PASSSECRE VARCHAR(20) NOT NULL,
   NOMBRESECRE VARCHAR(20) NOT NULL,
   CORREOSECRE VARCHAR(20) NOT NULL,
   TELEFONOSECRE NUMBER(10) NOT NULL

 );

ALTER TABLE  SECRETARIA
ADD CONSTRAINT PK_SECRETARIA PRIMARY KEY (RUTSECRE);



 CREATE TABLE MAYORDOMO
 (
   RUTMAYOR CHAR(8) NOT NULL,
   DVMAYOR VARCHAR(1) NOT NULL,
   PASSMAYOR VARCHAR(20) NOT NULL,
   NOMBREMAYOR VARCHAR(20) NOT NULL,
   CORREMAYOR VARCHAR(20) NOT NULL,
   TELEFONOMAYOR NUMBER(10) NOT NULL

 );


ALTER TABLE  MAYORDOMO
ADD CONSTRAINT PK_MAYORDOMO PRIMARY KEY (RUTMAYOR);




 CREATE TABLE PROFESOR
 (
   RUTPROFE CHAR(8) NOT NULL,
   DVPROFE VARCHAR(1) NOT NULL,
   PASSPROFE VARCHAR(20) NOT NULL,
   NOMBREPROFE VARCHAR(20) NOT NULL,
   CORREOPROFE VARCHAR(20) NOT NULL,
   TELEFONOPROFE NUMBER(10) NOT NULL

 );


ALTER TABLE  PROFESOR
ADD CONSTRAINT PK_PROFESOR PRIMARY KEY (RUTPROFE);





 CREATE TABLE PISO
 (
   CODPISO VARCHAR(6) NOT NULL

 );

ALTER TABLE  PISO
ADD CONSTRAINT PK_PISO PRIMARY KEY (CODPISO);




CREATE TABLE SALA
 (
   CODSALA VARCHAR(6) NOT NULL

 );

ALTER TABLE  SALA
ADD CONSTRAINT PK_SALA PRIMARY KEY (CODSALA);



CREATE TABLE SOLICITUD
(
  CODSOL VARCHAR(20)NOT NULL,
  FECHASOL DATE NOT NULL,
  PERIODO NUMBER(2,0) NOT NULL,
  SEMESTRE VARCHAR(20)NOT NULL,
  ANOSOL NUMBER()NOT NULL

);

ALTER TABLE  SOLICITUD
ADD CONSTRAINT PK_SOLICITUD PRIMARY KEY (CODSOL);



CREATE TABLE COMENTARIO
(
  CODCOM VARCHAR(20)NOT NULL,
  FECHACOM DATE NOT NULL,
  HORA NUMBER NOT NULL,
  ANOCOM NUMBER NOT NULL

);

ALTER TABLE  COMENTARIO
ADD CONSTRAINT PK_COMENTARIO PRIMARY KEY (CODCOM);



CREATE TABLE IMPLEMENTO
(
  CODIM VARCHAR(20) NOT NULL,
  TIPOIMPLE VARCHAR(30) NOT NULL,
  CANTIDAD NUMERO(3,0) NOT NULL,
  ESTADO VARCHAR (10) NOT NULL
);


ALTER TABLE  IMPLEMENTO
ADD CONSTRAINT PK_IMPLEMENTO PRIMARY KEY (CODIM);


ALTER TABLE  USUARIO
    ADD CONSTRAINT FK_USUARIO_SECRETARIA
    FOREIGN KEY (RUTSECRE)
    REFERENCES SECRETARIA(RUTSECRE);

ALTER TABLE  USUARIO
    ADD CONSTRAINT FK_USUARIO_MAYORDOMO
    FOREIGN KEY (RUTMAYOR)
    REFERENCES SECRETARIA(RUTMAYOR);

ALTER TABLE  USUARIO
    ADD CONSTRAINT FK_USUARIO_PROFESOR
    FOREIGN KEY (RUTPROFE)
    REFERENCES PROFESOR(RUTPROFE);

ALTER TABLE  SECRETARIA
    ADD CONSTRAINT FK_SECRETARIA_PISO
    FOREIGN KEY (CODPISO)
    REFERENCES PISO(CODPISO);


//EJEM
SELECT RUT,PASS FROM USUARIO U JOIN SECRETARIA S
ON S.RUTSECRE=U.RUTSECRE
WHERE RUT=RUTSECRE AND PASSSECRE=PASS;


//FORANEA DE COMENTARIO

ALTER TABLE  COMENTARIO
    ADD CONSTRAINT FK_COMENTARIO_PROFESOR
    FOREIGN KEY (RUTPROFE)
    REFERENCES PROFESOR(RUTPROFE);

ALTER TABLE  COMENTARIO
    ADD CONSTRAINT FK_COMENTARIO_SECRETARIA
    FOREIGN KEY (RUTSECRE)
    REFERENCES SECRETARIA(RUTSECRE);


ALTER TABLE  COMENTARIO
    ADD CONSTRAINT FK_COMENTARIO_MAYORDOMO
    FOREIGN KEY (RUTMAYOR)
    REFERENCES MAYORDOMO(RUTMAYOR);

ALTER TABLE  COMENTARIO
    ADD CONSTRAINT FK_COMENTARIO_SALA
    FOREIGN KEY (CODSALA)
    REFERENCES SALA(CODSALA);

//FORANEA DE SOLICITUD

ALTER TABLE  SOLICITUD
    ADD CONSTRAINT FK_SOLICITUD_SECRETARIA
    FOREIGN KEY (RUTSECRE)
    REFERENCES SECRETARIA(RUTSECRE);


ALTER TABLE  SOLICITUD
    ADD CONSTRAINT FK_SOLICITUD_MAYORDOMO
    FOREIGN KEY (RUTMAYOR)
    REFERENCES MAYORDOMO(RUTMAYOR);


ALTER TABLE  SOLICITUD
    ADD CONSTRAINT FK_SOLICITUD_SALA
    FOREIGN KEY (CODSALA)
    REFERENCES SALA(CODSALA);


//FORANEA DE SALA

ALTER TABLE  SALA
    ADD CONSTRAINT FK_SALA_PISO
    FOREIGN KEY (CODPISO)
    REFERENCES PISO(CODPISO);

ALTER TABLE  SALA
    ADD CONSTRAINT FK_SALA_IMPLEMENTO
    FOREIGN KEY (CODIM)
    REFERENCES IMPLEMENTO(CODIM);

//DOMINIO

ALTER TABLE USUARIO
  ADD CONSTRAINT CK_TIPOUSUARIO
  CHECK(TIPOUSUARIO IN (PROFESOR,SECRETARIA,MAYORDOMO));

ALTER TABLE IMPLEMENTO 
  ADD CONSTRAINT CK_TIPOIMPLE
  CHECK(TIPOIMPLE IN (PROYECTOR,BORRADOR,NOTEBOOK));

ALTER TABLE IMPLEMENTO
  ADD CONSTRAINT CK_ESTADO
  CHECK(ESTADO IN (REGULAR,MALO,BUENO));











